### ISSUE TITLE
Heating coil doesn't work

### ISSUE THREAD

**Issue by 5igm** [Glitchfiend/ToughAsNails#107]
![2](https://cloud.githubusercontent.com/assets/11610914/17845268/35f39c44-6873-11e6-9862-1af955c89ae7.png)
I have built 3 activated heat coils. Why my temperature is still going down?

**Comment by 5igm** [comment]
When the heating coil change to cooling coil or cooling coil change to heating coil immediately, there will be some wrong that cooling coil will increase temperature or heating coil will decrease temperature. For example like this device
![3](https://cloud.githubusercontent.com/assets/11610914/17863372/fd3d62c8-68cb-11e6-978b-e5d3e4dd8954.png)

![4](https://cloud.githubusercontent.com/assets/11610914/17863409/1e606586-68cc-11e6-937f-94452b0f4497.png)

**Comment by 5igm** [comment]
https://youtu.be/eXjptx7u_RI

**Comment by 5igm** [comment]
forge-1.10.2-12.18.1.2068-universal
ToughAsNails-1.9.4-1.0.11

**Comment by Scootty** [comment]
I don't know what this complex setup you have is but I can explain it simpler I believe.

After testing with 1 Cooling Coil and 1 Heating Coil using levers to activate them here's what I found: If you activate both in the same area the other is cooling/heating it's gonna get glitched instead of what you logically think would happen with both on, warm temperature. What actually happens when you turn both on at the same time is the one that was activated first continues it's effects while the other has no added effects. Even turning off the first one doesn't change the temperature.

To fix this issue, turn both off and leave the area until your temp reverts back to the environments temp. A good example of this is if you have a heating/cooling coil in your house and bug them, to fix the bug turn both off, go outside for...about 10 seconds somewhat far away from your house until the environments temp kicks in then just go back in and only activate 1 at a time.

As far as I can see, you will not get bugged by this if you turn off the active one then activate the other.

**Comment by 5igm** [comment]
@Scootty Could you fix it? I means when turn on cooling coil and heating coil at the same time, the room will be not heated or cooled.

**Comment by Scootty** [comment]
I don't have access to this mods code, sorry. However, in your video it shows you doing what I had mentioned above. Just avoid turning both on in the same area.

As far as it not producing any heat or cooling, I can see what appears to be glass in your roof from the second picture. The developer has stated that the coils don't work with transparent roofs (Glass) or houses with no roofs. In those spots where glass is a part of the roof no cooling/heating will exist I don't think.
