### ISSUE TITLE
Problem: After death, players' statue don't been reset| Suggestion: Please add some permissions

### ISSUE THREAD

**Issue by 5igm** [Glitchfiend/ToughAsNails#108]
After death, players' statue don't been reset. (Players is dehydrated and players' body temperature is as same as the statue before player died.)
I suggest at least adding an option to reset players' statue after death.

And, I think "/tan tempinfo" is a very useful command, because orb in the middle of the HUD sometimes cannot shows the correct body temperature especially after death. (Thirst system has the same problem)
Thereby, I suggest to offer some different permissions for each command.

**Comment by CiaranKennedy** [comment]
Im going to bump this suggestion rather than make a duplicate one. As a server admin I was very dissapointed to find that I couldnt let players use the HUD with /tan tempinfo without giving them access to the commands to change season or change their temp. It would make a lot of sense to have these commands have different permission nodes, or at least have a seperate node for the "OP" commands like settemp and  setseason
