### ISSUE TITLE
Over Heatsources and Mod-Support?

### ISSUE THREAD

**Issue by cyberpunkbln** [Glitchfiend/ToughAsNails#109]
Hello,
ist it possible to bring other heatsources for heating up in the game?

Like torches, the oven and so on, and other heat-sources from mods?

thx

**Comment by DrTeath** [comment]
I've been experimenting with this mod in a modpack I'm making and I'm really liking the concepts.
As cyberpunkbln asked for above, we need cross mod integration. Both for players and pack makers. 
I would suggest, creating json configuration files for all heating/cooling, thirst and the 'lifeblood' effects. 

Instead of having everything hard-coded and therefore inaccessible to pack developers. All items, armours and blocks that effect heat should be able to be made compatible simply by adding them to a json. Having the inbuilt items be modifiable in this way would also be advantageous.  This would put the onus for compatibility and balance on modders, pack makers and players.

I would also suggest that each type be give its own folder and read in all relevant scripts on start-up (or by using /tan reload console command in game), rather than requiring a single master json. Similar to the way minetweaker/modtweaker work, any number of different script files can be added with out needing to be merged by the pack makers.

Example stolen from https://github.com/Jozufozu/ExNihiloOmnia

{
  "Temperatures": [
    {
      "block": "minecraft:furnace",
      "meta": 0,
      "heatpertick": 2,
      "radius": 5
    },
    {
      "block": "minecraft:packed_ice",
      "meta": 0,
      "heatpertick": -2,
      "radius": 5
    }
  ]
}

**Comment by hanleybrand** [comment]
This is a good idea - I actually came here to try to figure out if there was a way to make the Druidry camp fires generate heat.
