### ISSUE TITLE
[Suggestions] Coal filter, Campfire and Canteen

### ISSUE THREAD

**Issue by Scootty** [Glitchfiend/ToughAsNails#113]
So I've been playing with this mod for awhile, but just thinking about it I feel like it's too expensive to make these things so far. I mean with dirty water you get 1.5 thirst and I don't even notice the negative effect so far but the water source never runs out right and you have to sacrifice 6 papers and 3 charcoals (does it work with coal? not sure but that's basically an entire tree) all for 3.5 thirst so it doesn't feel like the trade is worth the result. I'd discard the whole filtering process because I mean, you can get clean water by just boiling it I think. I watched a couple vids and read a couple things about that, also made me question the "clean water via rain collector" thing, because isn't that like...ocean water? full of salt? dangerous to your health?

Same thing with the campfire, it costs an entire tree to make one. I'd suggest replacing it with sticks.

Similar with the Canteen, it costs a couple cows to make one. Actually imo, it should only cost like one or something and adding in like leather strips or something to follow that recipe because a couple cows for leather armor to make a chest plate somewhat makes sense (or maybe not) but a couple cows for a Canteen? Nah.

**Comment by ruyanve** [comment]
The negative effect of dirty water seems to be bugged atm, this will hopefully be fixed in the future.
I don't think the crafting recipes are too expensive, even tho I run a very hardcore setup. I would actually like to see a hardcore mode config option to make it more expensive! :-)
I hope the rain at your place it not salty. The way rain works is actually quite interesting and involves water going from a liquid form to gaseous and since salt doesn't make the same transition (at that low temperature) it stays behind thereby separating salt and water. 
Anyway, rain water is not salty and, if not polluted by other means, no danger to your health. But before you go out and drink rain water, inform yourself about the quality of it in your area! ;-)
