### ISSUE TITLE
[1.11] Crash with TAN when loading server

### ISSUE THREAD

**Issue by Morpheus1101** [Glitchfiend/ToughAsNails#142]
crashlog @ https://puu.sh/ssRKd/fc466eeff2.txt

**Comment by Adubbz** [comment]
You need to update the mod to 2.0.2. Please check closed issues in future, this crash has been brought up quite a few times.

**Comment by Morpheus1101** [comment]
I am using version 2.0.2 :)

**Comment by Adubbz** [comment]
Your crash log tells a different tale:

`TANLoadingPlugin (ToughAsNails-1.11-2.0.1.jar)`
and
`toughasnails{@MOD_VERSION@} [Tough As Nails] (ToughAsNails-1.11-2.0.1.jar) `

The version in the crash log is the real version you have installed. If you're using a custom launcher, it may be a bug present in that, since I've seen a few people run into similar problems as a result of version confusion lately

**Comment by Morpheus1101** [comment]
Yeah i understand that the log sais 2.0.1 but i dble checked an mods list shows 2.0.2

![mmd](https://cloud.githubusercontent.com/assets/10524952/20597068/4a949fcc-b28d-11e6-8a62-354f18cd1c31.png)

**Comment by Morpheus1101** [comment]
Server is launched using this script which is normally a batch file: 
[LaunchServer.txt](https://github.com/Glitchfiend/ToughAsNails/files/611185/LaunchServer.txt)

Line 114 shows 2.0.2 loaded in the log below

[fml-server-latest.txt](https://github.com/Glitchfiend/ToughAsNails/files/611192/fml-server-latest.txt)

**Comment by Adubbz** [comment]
Are you certain you're launching the correct modpack here? It seems there's mods present in your files that aren't loaded at all on your server, as well as other version mismatches with Forge (You're launching 2157, but infact it's 2153), BoP (2106 instead of 2110), actually additions and probably others as well

**Comment by Morpheus1101** [comment]
im not 100% sure now whats happening as i cant reproduce, so *shrug* apologies if it seemd i wasted your time

**Comment by Adubbz** [comment]
Hrm, perhaps you thought you restarted the server after updating everything but accidentally didn't? Not sure, in any case, glad you got it working :)
