### ISSUE TITLE
Bugs and requests

### ISSUE THREAD

**Issue by PingPongLee** [Glitchfiend/ToughAsNails#152]
Very nice mod! I have some things to mention

First of all im running this mod with other mods:
Minecraft 1.10.2
Forge 12.18.2185
ToughAsNails-1.9.4-1.0.11
Biomes O Plenty 1.10.2-5.0.0.2109
RTG-1.10.2-4.1.1.8 (Realistic  Terrain Generation)
BiomeTweaker-1.10.2-2.1.230 (For RTG to work with BOP)
DrZharks MoCreatures Mod-10.0.6

"Bugs"
1. - I'm currently using this mod on a server and my Seasons is bugging out big time. If i go to sleep in like early_summer i will wake up in a random other season like late_winter . I don't think this happened right away with my server but began happening after a few days. 
2. - Getting the Thirst effect doesn't really do much atm, but i see this is mentioned by others so i wont go further into it (but have a suggestion down below

Suggestions
1. - Make furnaces which are burning, also heat you up
2. - If possible, let the user not cool down as fast if they are indoors
3. - When the thirst effect is enabled let it also drain your hunger bar, just like when you get food poisoning. Why ? Because drinking bad water could cause the same as food poisoning 
4. - Make it more configurable. Like length of season, speed which you get warmer / colder, amount a canteen can contain etc. 

Well.. This was really i had to say, i expected the list to be longer, when i began.. This just means that the mod is very very good! I really enjoy playing with it

**Comment by PingPongLee** [comment]
Bug 1 seems to have been fixed in [47e618e](https://github.com/Glitchfiend/ToughAsNails/commit/47e618ef92cf6c4fa81dbef0ef148cd9a228d3a3), but will you release it for 1.10.2 ?

**Comment by Adubbz** [comment]
Bugs

1. As you mentioned, it has indeed been fixed already. I'm not personally going to be doing backports for BoP or TaN, however pull requests are still welcome and I'll submit a new release.

2. An issue already exists for this with https://github.com/Glitchfiend/ToughAsNails/issues/111

Suggestions

1. An issue exists for this with https://github.com/Glitchfiend/ToughAsNails/issues/101 (albeit under a not-so-great title)

2. Perhaps in the future, although right now I feel like this would would be rather complex to implement without a huge payoff in terms of making the temperature system better overall.

3. Though indeed this may happen in real life, I don't really think it's intuitive for a game. I'd expect I'd be seeing quite a few bug reports about 'bad water gives me food poisoning', which is never fun to deal with. The thirst effect is intended to provide all of the negative consequences for drinking dirty water, although at some point we'll have to look into it since it sounds like it currently isn't severe enough

4. An issue already exists for this also, with https://github.com/Glitchfiend/ToughAsNails/issues/26

Thanks for playing the mod, I'm glad you enjoy it :)
