### ISSUE TITLE
Configuration options (Freezes)

### ISSUE THREAD

**Issue by RiverC** [Glitchfiend/ToughAsNails#161]
It should be possible to disable freezes entirely, or at least alter the biomes that they spawn in. If there is some way to integrate with BiomeTweaker to alter their spawn location, that would be very helpful to know. 

I'd prefer to not have to do something drastic to remove them, but they get in the way of the play balance of the modpack I'm working on.

Edit: for example, this is possible with BiomeTweaker

hellBiome.removeSpawn("net.minecraft.entity.monster.EntityPigZombie", "MONSTER")

But what I don't know what the entity name is for the Freeze. Using these commands, in theory you could alter where they show up. (I also don't know if they're part of MONSTER spawns either.)

Any help with this is appreciated.

**Comment by OneChipBob** [comment]
I feel the same way about altering the biomes that Freezes can spawn in, but for the opposite side of things.  I generated a 16,000 x 16,000 world with the default biomes 'o plenty config and ended up with zero ice plains or ice mountains.  Is it possible to configure any of the other winter focused biomes to spawn Freezes or could it even be setup so that they could spawn on any snow or ice block, making it similar to how Quark has changed where Blazes can spawn?

**Comment by RiverC** [comment]
You can use BiomeTweaker! I personally made it so there was a banded-climate world that starts you in the arctic (you have to travel south for warmer climes - or much father north) 

Later I'll find my line which altered the spawn behavior of Freezes so you can use BiomeTweaker to expand their spawn. 

You may also wish to try some banded climate settings as well, which will more coherently group climate (though not perfectly - real climate doesn't follow simple bands but is affected by gross wind and water patterns, c'est la vie!)
