### ISSUE TITLE
Extreme Lag from coils

### ISSUE THREAD

**Issue by p455w0rd** [Glitchfiend/ToughAsNails#165]
I'm trying to work on a 1.10.2 addon that expands on the coils. There is a bug where as time goes on and the the loops check further and further out, FPS drops to unplayable levels. I let it go until I was getting 1 frame every 10 seconds or so. Same happens on 1.11. Just place a coil, give it redstone signal and let it go for ~5 minutes.

**Comment by Adubbz** [comment]
Have you enabled the fireballs debug option? Since they are know to cause severe performance issues, hence why they're only for debugging. Additionally under what conditions are you testing this? Coils should not be able to spread without a roof, and cannot go through walls or terrain. If this is happening then you may have broken something

**Comment by p455w0rd** [comment]
Did not enable debug. I am inside a completely contained box of grass blocks. Inside area is 3x4x3 of air blocks minus the cooling coil. Cooling coil is set up in the corner which is powered through the block below which has a redstone torch below it. Tested with only TAN loaded. Also tested by removing a block from the wall exposing the outside and it still happens.

**Comment by Adubbz** [comment]
This appears to have been as a result of snowflake particle collisions rather than the update checking. Could you please double check in a profiler in future, performance issues can't always be attributed to the 'obvious answer'
