### ISSUE TITLE
Add fireplaces, chillers, and ventilators

### ISSUE THREAD

**Issue by Forstride** [Glitchfiend/ToughAsNails#18]
Fireplaces and chillers need to be added to control the temperature in buildings.  They can be used to heat/cool single rooms.

Ventilators need to be added to remove gases from caves, and keep air clean.  In addition to ventilators, creating a vent hole from the surface to a cave should increase air quality in that area of the cave.

**Comment by TinkerWorX** [comment]
Assuming my [suggestion](https://github.com/Glitchfiend/ToughAsNails/issues/11#issuecomment-226723764) is possible, could this be made to work with enclosing spaces, like making a house and then having some sort of CO2 scrubbing or Oxygen generation going.

**Comment by Forstride** [comment]
I'm still not really sure how we're going to handle air quality TBH.  I don't want it to get to complex, because then it wouldn't be fun.  We're trying to keep each major component of the mod fairly simple and easy to understand, while still feeling like important gameplay elements.

**Comment by TinkerWorX** [comment]
It does sounds like a complicated mechanic to implement in an enjoyable way. I'm looking forward to seeing what you come up with.

**Comment by Cat09** [comment]
I'd suggest having a config setup for varying degrees of complexity, for a slider on the realism / simplicity, and computational load scales.
depending on how detailed you get, forestry might pick this up as a dependency for their greenhouses. or ask to nab some code ;)

**Comment by skruis** [comment]
I can think of 3 ways. 

For basic air quality that's not affected by other gases, the first simply being 'depth'. Instead of getting air channels to the surface, you also could introduce air as a 'liquid' that's transportable via pipes. You can then pump 'air' from surface collectors to 'vents' underground. If you're within X blocks of a vent, you then have good air quality. If you're outside of the radius of an active vent, you then need tanks and a breathing mask at certain Y levels.

The 2nd and 3rd are how air is affected by other gases. Perhaps if you have a gas 'source' block, the impact of the gas on air quality could be factored in by the height of the area the gas occupies? I guess that could be appropriate for gases that are 'lighter' than breathable air. And then the opposite for heavy gases which will trend lower in the room they occupy. Example: let's say you have ... helium (i have no idea how realistic it is to have helium naturally generate) and it's a light gas. In a 25x25x25 room, helium would 'rise' to the top of the room so the air quality in the upper blocks would be worse than those in the lower blocks depending on the strength of the source (which could be a factor of how many source blocks are in given area). Then if you have a heavy gas, Gas X (I don't know any heavy gases), that gas would occupy the lower portions of the 25x25x25 room and the air quality would be worse in the lower sections of the room. Let's say you're in a chasm and there's a heavy gas, the gas, depending on the source strength, would fill a certain amount of air blocks in the bottom of the chasm ... kind of like a flowing liquid.

**Comment by Forstride** [comment]
That's a bit uhhh, beyond the scope of the mod.  It's not a tech mod.  It's a survival mod.  I'm not interested in making the mechanics complicated like that.

**Comment by Cat09** [comment]
just had a thought, should nether portals be heat sources? might be neat, depending on how portals are "supposed" to work.

**Comment by pastellexists** [comment]
Air quality could potentially work like temperature, with different sources being detrimental to it. 

fire -5
leave block +1
grass block +0.1
lava -10
and so on

With less than 25% air quality you begin suffocating. With more than 85% air quality you begin getting bonuses.

Of course I'm too lazy to run mathematics, so my math on the plus and minuses on blocks is probably way off compared with my air quality bonuses and detriments.
But air quality should not be visible by a gauge. Cause you can't really tell the air quality from your body very well.

**Comment by Forstride** [comment]
It's a game.  You can definitely tell when the air quality around you is bad though (Harder to breathe, choking, coughing, etc.).  The gauge will replace the oxygen meter when you're not underwater, and will only appear if the air quality is bad.
