### ISSUE TITLE
1.10.2

### ISSUE THREAD

**Issue by grundyboy34** [Glitchfiend/ToughAsNails#199]
I've noticed the 1.9.4 branch, which also serves 1.10.2 players, hasn't been updated. Could the commits from the 1.11 branch be pulled into 1.9.4 so that 1.9.4->1.10.2 players can have the same updates?

**Comment by Adubbz** [comment]
Though Git does indeed allow for that, I'm afraid it's not always that simple. With 1.9.4/1.10.2 something like this could be done with relative ease, but between 1.10.2 and 1.11 there were changes to MCP names as well as the code itself that may not necessarily be compatible. If someone confirms that certain commits can be applied with no additional changes made then I can apply them and release a new version for 1.10, but otherwise I'm not really looking to make and test the same changes twice for two different versions.

**Comment by grundyboy34** [comment]
I'll comb through the commits tomorrow and manually merge them to my own fork for testing before sending you a pull request.
