### ISSUE TITLE
[Suggestion] Config to enable RF on heating/cooling coils

### ISSUE THREAD

**Issue by grundyboy34** [Glitchfiend/ToughAsNails#201]
I'm unsure of your stance on adding RF/Forge Energy support for some TAN blocks, but I think it would make for a good addition, especially for heating/cooling coils. This functionality could be toggled via a config, that when off, has the default behavior of requiring redstone, and when enabled, instead requires RF/Forge Energy.

**Comment by Adubbz** [comment]
I think the fuel idea mentioned here would be the best approach: https://github.com/Glitchfiend/ToughAsNails/issues/81
Possibly an additional block to transform rf to cooling or heating would be suitable as well, but that would come after fuel is implemented.

Closing this though since this issue is pretty much the same as the one I linked above.
