### ISSUE TITLE
[Bug Report] Game Crash

### ISSUE THREAD

**Issue by Baylem** [Glitchfiend/ToughAsNails#252]
Hello. I have found an issue revolving around the Iceball which is fired from the Freeze entity.

Here is the needed information from my log:

Mod Version: 1.0.11 and 1.11

```
Time: 5/21/17 8:02 PM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
at toughasnails.core.ClientProxy.spawnParticle(ClientProxy.java:93)
at toughasnails.entities.projectile.EntityIceball.func_70071_h_(EntityIceball.java:223)

-- Entity being ticked --
Details:
Entity Type: ToughAsNails.iceball (toughasnails.entities.projectile.EntityIceball)
Entity ID: 392
Entity Name: entity.ToughAsNails.iceball.name
```

The particular line of code from Iceball.java is line 233 with the code
https://github.com/Glitchfiend/ToughAsNails/blob/TAN-1.11.x-2.0.0/src/main/java/toughasnails/entities/projectile/EntityIceball.java#L223
```java
ToughAsNails.proxy.spawnParticle(TANParticleTypes.SNOWFLAKE, this.posX, this.posY + 0.5D, this.posZ, 0.0D, 0.0D, 0.0D, new int[0]);
```
The other listed error is in the method itself at:
https://github.com/Glitchfiend/ToughAsNails/blob/TAN-1.11.x-2.0.0/src/main/java/toughasnails/core/ClientProxy.java#L93
```java
entityFx = new EntitySnowflakeFX(minecraft.world, x, y, z, MathHelper.nextDouble(minecraft.world.rand, -0.03, 0.03), -0.02D, MathHelper.nextDouble(minecraft.world.rand, -0.03, 0.03));
```

To recreate this game crash:

1) You need to spawn in a Freeze
2) Let the freeze fire at you but pause the game before the Iceball hits you (does not need to be on a colliding path with the player)
3) Leave the world
4) Attempt to rejoin the world.

**Comment by Robijnvogel** [comment]
I could reproduce this.
2. the Iceball does not need to be on a collision course with the player.

world == null

Starting my IDE as we speak.

**Comment by Robijnvogel** [comment]
Can be fixed by adding _World parWorld_ to the parameters of [_CommonProxy#spawnParticle_](https://github.com/Glitchfiend/ToughAsNails/blob/TAN-1.11.x-2.0.0/src/main/java/toughasnails/core/CommonProxy.java#L13).
In [_ClientProxy#spawnParticle_](https://github.com/Glitchfiend/ToughAsNails/blob/TAN-1.11.x-2.0.0/src/main/java/toughasnails/core/ClientProxy.java#L86), each mention of _minecraft.world_ should be replaced by _world_.
[_EntityIceball_](https://github.com/Glitchfiend/ToughAsNails/blob/TAN-1.11.x-2.0.0/src/main/java/toughasnails/entities/projectile/EntityIceball.java#L223) and [_EntityFreeze_](https://github.com/Glitchfiend/ToughAsNails/blob/TAN-1.11.x-2.0.0/src/main/java/toughasnails/entities/EntityFreeze.java#L105) can both pass _this.world_ as a parameter. [_BlockTANTemperatureCoil#randomDisplayTick_](https://github.com/Glitchfiend/ToughAsNails/blob/TAN-1.11.x-2.0.0/src/main/java/toughasnails/block/BlockTANTemperatureCoil.java#L99) has a _World world_ parameter that can be passed on.
