### ISSUE TITLE
Question regarding temperature configs

### ISSUE THREAD

**Issue by Sunconure11** [Glitchfiend/ToughAsNails#284]
Is it possible to set a block to give a negative value, and thus, put out a negative temperature? If not, could this be implemented for configs in a future update?

**Comment by mcdodge34** [comment]
I support this, Ice would normally lower our temperature down, packed ice even more perhaps, but at the same time, it would defeat the machines purpose of the mod.

**Comment by bob0bob** [comment]
There is a config file for block temperature.  I've added many items to mine.  Even added lit torch to add a little heat.  It appears to work for me.

Wish there was a biome adjustment.   I would like to over ride it. but have not looked at forge to see if they allow it.  Since this mod realize on forges default value for the biome default temps.

**Comment by Adubbz** [comment]
Negative values should indeed already be supported.

**Comment by Br1anSimon** [comment]
> 

How do you add different items to your config file?
