### ISSUE TITLE
Biomes o plenty compatibility

### ISSUE THREAD

**Issue by Mrkol** [Glitchfiend/ToughAsNails#292]
I've spent more than 3 hours trying to find a biome in which the freeze mob spawns with biomes o plenty installed, and still did not succeed. From this I conclude that "ice plains" and "ice hills" either do not generate at all or are extremely rare with BOP, therefore making freeze rods unobtainable. Obvious fix for this would be making freezes spawn in BOP snowy biomes like snow forests and ice oceans.

**Comment by mcdodge34** [comment]
I remember there's a recipe for them in Forever Stranded modpack, so perhaps, you could check it out and import it into your modpack for now, that is what I'll do for mine since I also use BoP and finding vanilla biomes is sometimes really really challenging, even if I want the mod to be active only on other planets and some space stations from advanced rocketry, I will still need to find theses Freezes and if they only spawn in Vanilla snowy biomes, I think I'll need a recipe for them.
