### ISSUE TITLE
Camel Pack?

### ISSUE THREAD

**Issue by Louis9902** [Glitchfiend/ToughAsNails#30]
I like the mod but it's a little bit annoying to have constantly someting like waterbottles in you inventory.
Maybe someting like a Camel Pack can be useful. So that in the early game you hame sometong to go mining without a full inventory filled with Waterbottles.

**Comment by Forstride** [comment]
I'm not a big fan of the camel pack personally.  I just don't like the idea of something that you just equip and forget about I guess.

I mean, you should generally be able to find water underground fairly easily, but I'll look into other options for this kind of thing.  One idea I thought of was dew leaves that would drop randomly from leaf blocks if you harvest them in the morning, and they could be a stackable item since no other thirst-restoring items are.

**Comment by Biochao** [comment]
Terrafirmacraft has a feature where you can right click on water with an empty hand to restore a very small amount of thirst. The idea being you are cupping your hands together to sip from the river.

**Comment by Forstride** [comment]
I was originally going to implement that, and I had started working on it, but I forget why we decided to scrap it completely.  I think it was just because having a canteen and drinking straight from water blocks would basically act the same.  The only difference being canteens can be drank from 3 times before needed to be refilled.

**Comment by Louis9902** [comment]
I think the idea with the leaves is very good.
