### ISSUE TITLE
General mechanic question/concern

### ISSUE THREAD

**Issue by Y0ungSandwich** [Glitchfiend/ToughAsNails#329]
Love the mod but I have one concern that doesnt make much sense for a mod of this type. 

How come if I have a lit furnace I will get +10 heat near it and if I have 2 or more lit furnaces around me I still only receive +10 heat?  I figured the surrounding blocks would all take account for the heat level in that area. 

Or am I simply looking at something wrong?

**Comment by Adubbz** [comment]
This is actually intentional. In the past we had it so these would stack, however with things like lava this just doesn't work well, because the depth of a given lava pool may cause the temperature to severely increase as opposed to just the proximity as is intended. Right now we just pick the 'most extreme' temperature out of the modifiers around you, whether it be fire, lava, or whatever, and apply it once.

**Comment by TimTinkers** [comment]
@Adubbz can we make this configurable? I didn't realize this behavior changed from 1.10.2.
