### ISSUE TITLE
Can TAN's season become 'texture pack FREE'?

### ISSUE THREAD

**Issue by Phalaaange** [Glitchfiend/ToughAsNails#338]
TAN's the most 'seasoning' mod I've ever wanted. But texture pack would hide it's original seasoning effect, like grass blocks turning yellow.

But I notice that texture pack's texture won't necessarily stay the same! the MC's geographic difference would affect the grass blocks' color even when they're in a texture pack!

If TAN's color-changing effect would base a mechanism similarly like this, I don't know, would that be great?

**Comment by Adubbz** [comment]
I'm really not quite sure what you're talking about here... TaN doesn't alter the default textures in any way? If you're referring to biome-specific grass colours, those are not substituted seasonally and that is intentional. Many of our biomes in Biomes O' Plenty make heavy use of custom grass/foliage colouring and would not look correct without it. Hence, we merely adjust the colours rather than replace them entirely.

**Comment by Phalaaange** [comment]
Oh, I get it.
Put it this way, is there any suggestion how I can adjust non-default texure pack into mapping the seasoning effect?
I wonder this because texure packs, like the default texture, have biome-specific color mapping.

**Comment by Deide** [comment]
Which part of the colormap does TaN use for oak trees? I use Dokucraft and while the Betterfoliage leaves turn orange-brown in the Autumn, the leaves themselves stay green. It works as expected with default textures, so it seems like a colormap problem to me.

**Comment by Phalaaange** [comment]
exactly, same thing happened to Dokucraft's BOP support. But when I changed to Dokucraft 1.12, I noticed that minecraft:grass's color did change a bit thru seasoning. I guess it was the texture packs's colormaping  problem?

**Comment by Adubbz** [comment]
TaN does not use textures in any way for seasonal colouring. We do not use the colour map or anything like that simply because there is no reason for us to. We take whatever the existing colour is, and adjust it. That's it. Minecraft still handles how the colouring is applied to the grass, and all of the textures, we just adjust the numerical colour value it is supplied with.

**Comment by KnightMiner** [comment]
It sounds to me like a extended resource pack feature from Optifine /mcpatcher is being used, which runs after TAN's coloring. So not really an TAN issue but the way the other mod overrides biome colors.

**Comment by Phalaaange** [comment]
geez, I get it now. thx guys!
