### ISSUE TITLE
Permanently reduced maximum life after disabling mod.

### ISSUE THREAD

**Issue by CaptainPepperjack** [Glitchfiend/ToughAsNails#35]
After realizing the thirst and heat mechanics are too hardcore for me I removed the mod but my maximum HP remained 3 hearts lower than normal.

**Comment by Adubbz** [comment]
We currently use Vanilla's builtin system to change Max health and add our own 'spices' to make it more friendly. There's not a whole lot that can be done if the mod is removed, although I the config toggle can be changed to reset current worlds. 

For the time being, you could reinstall the mod, and give yourself and use lifeblood crystals to restore your health to the max level, then remove it. Otherwise you'll need to mess with NBT which isn't very fun.

I might have to see if there's a nicer way of implementing the feature such that it isn't persistent after removing the mod, but for now, I think the above is your best option

**Comment by Cat09** [comment]
I've found an NBT editor to be very useful for fixing other things, so you may want to pick one up anyway. Perhaps this mod could add a  `'maxhealth' {'set', 'reset' {'TAN', 'vanilla'}}`  but that wouldn't fix the post-uninstall issue.
changing to a permanent non-removable buff system could work, if you implemented custom health effects?

**Comment by pastellexists** [comment]
Could also add something like /tan disable which would reset the health and disable the mod via forge.

**Comment by Forstride** [comment]
I've removed the Lowered Starting Health feature, so this issue can be closed.  You'll have to re-up your health with an NBT Editor
