### ISSUE TITLE
White screen during winter.

### ISSUE THREAD

**Issue by rumci** [Glitchfiend/ToughAsNails#355]
When winter comes i have white screen, but only in house/closed space. https://goo.gl/QPr1we
I also use oder mods, but my friends on this same server and with this same mods, don't have this problem. I tested this on other laptop and have this same problem there.

**Comment by rumci** [comment]
I thought I fixed this but nope. It (white screen) only happens during snow-fllury. Any ideas? :)

**Comment by Adubbz** [comment]
I'm pretty sure this is another mod. That winter overlay in the top left isn't ours, and we don't touch snow rendering. If this was a problem with TaN, the white would be overlapping the shield (it's not).

**Comment by Forstride** [comment]
Ok, first of all, you have Harvest Festival installed, which also adds seasons.  I don't think there should be any conflict between them, but you should really make sure than TAN's seasons are even enabled first.

Second, this just isn't something that would be caused by TAN.  You said no one else on your server has this issue, so something is clearly happening client side with a mod that affects the rendering of the game.

If you have OptiFine installed, try removing that and seeing if the issue is fixed.  If not, I can't really help you, because it's more than likely not an issue with TAN.
