### ISSUE TITLE
Config parameter to make temperature more forgiving?

### ISSUE THREAD

**Issue by Thissthing** [Glitchfiend/ToughAsNails#373]
I dislike how fast the temperature changes. It becomes too much of a nuisance. I tried changing the rate of temperature change to make it slower, but that results in unrealistic gameplay. You should add a config parameter that lets you change how forgiving the temperature system is. 

Let's say you're freezing to death, placing one or several campfires should quickly bring back your temperature to the equilibrium, quicker than it goes back down after the campfires get extinguished. That would be more realistic. If I change the rate, then it takes equally long to reach the equilibrium than it takes to deviate from it. There should a parameter that lets you make the whole temperature system more forgiving, to allow the mod to be less of a nuisance and more enhancing of realistic gameplay.

**Comment by Adubbz** [comment]
Making the temperature system 'more forgiving' is kind of vague. All of the parameters we use for the temperature system are already configurable. It is intentional that it takes equally long to warm up as it does to cool down, because the same situation you describe is applicable to hot climates where you want to cool down. We don't want to make it near impossible for the temperature to leave the equilibrium range because otherwise there really isn't any point for the temperature system to exist. The whole idea is to leave it to the player to manage their temperature rather than us do it for them.
