### ISSUE TITLE
Crash in Dev Workspace

### ISSUE THREAD

**Issue by Terrails** [Glitchfiend/ToughAsNails#398]
I have an mod which has TAN support, but now from the looks of it ASM is crashing the game. Tried it without TAN and I could access the class (`net/minecraft/client/renderer/EntityRenderer`) without the exception.
[The log](https://gist.github.com/Terrails/a919807837bc04ec2cd62d991b45dcb7)

**Comment by Adubbz** [comment]
Could you please provide the full log? It also seems the jar file has been renamed, did you obtain it from our CurseForge or somewhere else (or did you rename it yourself)?

**Comment by Terrails** [comment]
I got it from curseforge but renamed it (ToughAsNails-1.12-3.0.0.71-universal.jar), also deobfuscated it with BON2, and placed it in libs folder
[whole log](https://gist.github.com/Terrails/b916a20ff576214d95eedab0d2c45962)

**Comment by Adubbz** [comment]
Ah I see, for future reference we have official deobf builds here: http://files.minecraftforge.net/maven/com/github/glitchfiend/biomesoplenty/ToughAsNails/. It seems the issue is that the MCP names were changed in 1.12.2, but we never updated our dev environment since existing builds still work fine outside of it (because they don't rely upon MCP names).

**Comment by Terrails** [comment]
For now I got the API because thats the only thing I need, gonna wait for the newer build (I like having the whole deobf because I can test it straight away without building and trying it on normal client), or I could just downgrade my mappings
