### ISSUE TITLE
Crash with most recent 1.10.2 release?

### ISSUE THREAD

**Issue by Roenais** [Glitchfiend/ToughAsNails#418]
My game crashes on load when using the newest version of Tougher than Nails for minecraft 1.10.2. Going back to the previous version of the mod seems to work fine. 

Crash Log:
https://pastebin.com/WXDM5M3y

**Comment by Adubbz** [comment]
You need to install Glitch Core. It's listed in the dependencies on CurseForge (as well as the changelog, and on Twitter). Here's a link: https://minecraft.curseforge.com/projects/glitchcore/files/2520829

**Comment by Roenais** [comment]
there are no dependancies listed on curseforge, as far as i can see. but thankyou for letting me know!

**Comment by Adubbz** [comment]
Curse puts them at bottom of the individual file’s download page. A bit hard to see sadly, but it is indeed there

**Comment by KnightMiner** [comment]
Why does the mod not state GlitchCore as a dependency itself? It would give a proper error screen instead of an unhelpful crash.

**Comment by Adubbz** [comment]
It's not possible because depending on the version of the game, a different version of GlitchCore is required. We can  possibly customize the crash to be clearer but we can't use Forge's existing dependency screen as far as I know.

**Comment by KnightMiner** [comment]
You dont need to supply a version though. Just saying the mod is requirdled is an improvement.

**Comment by Adubbz** [comment]
I guess, although it does mean similar crashes may occur in the future when we depend on higher versions of GlitchCore

**Comment by srs-bsns** [comment]
@Adubbz you can just add it to the `dependencies` in the @Mod annotation without a version range, and it will work as needed if __no__ instance of glitchcore is found.
Obviously, you won't be able throw an exception based on an unsupported version of glitchcore being loaded (since a dependant mod can't see into the future), but atleast it will be more informative if a user hasn't loaded glitchcore at all.

https://github.com/Glitchfiend/ToughAsNails/blob/TAN-1.12.x-3.x.x/src/main/java/toughasnails/core/ToughAsNails.java#L29
```java
    dependencies = "required-after:forge@[1.0.0.0,), required-after:glitchcore"
```

The same can be done with your other mods that also depend on glitchcore.

**Comment by Adubbz** [comment]
Yeah I think that's what I'll go with then. Worst case scenario we'll just ditch GlitchCore and go back to supporting 1.12 only with no dependencies, but it's something I've wanted to try for awhile so it is worth a shot.
