### ISSUE TITLE
[SUGGESTION] More realistic but more CPU-intensive physics

### ISSUE THREAD

**Issue by Tumlinh** [Glitchfiend/ToughAsNails#430]
From what I understand the temperature of nearby blocks is only determined by the hottest block around.
I made no benchmark for analysing the actual impact on CPU usage, but if it's not too intensive it would be cool to implement those features:
-compute the target temperature based on every nearby block and depending on the distance between players and hot blocks (exp function?) (detection distance of nearby blocks could be configurable for servers lacking horsepower)
-sinusoidal time modifier

**Comment by mathgeniuszach** [comment]
It shouldn't really be too complicated, because the mod goes through all of the nearby blocks in about a 2.5 block radius anyway. The only thing you would have to do different is add a multiplier to each block temperature, add the block temperatures together (or just pick the hottest and coldest blocks and add them together), and probably increase the block radius of checking (this would best be in the config). Code to change is in the ObjectProximityModifier.java class, and it literally says above it `//TODO: Replace this with something better`. Got any more ideas for it?

**Comment by mathgeniuszach** [comment]
Actually, come to think of it, there are only hot block modifiers in the base config. If a player used a colder value on a block it would overcome the hotter values instead of melding with them to make a mixture. It may make more sense to add another class for cold blocks in addition to the hot ones. I'll check it out some more.
