### ISSUE TITLE
[Bug] TAN won't let a Forge server start on Gentoo Linux

### ISSUE THREAD

**Issue by sverinn** [Glitchfiend/ToughAsNails#469]
OS information: Linux (amd64) version 3.0.6-gentoo

The same package works fine on Windows.

Clean server without any mods:
[fml-server-1.log](https://github.com/Glitchfiend/ToughAsNails/files/1843858/fml-server-1.log)

The same server with only TAN installed:
[fml-server-latest.log](https://github.com/Glitchfiend/ToughAsNails/files/1843854/fml-server-latest.log)

Pls halp :(

**Comment by Adubbz** [comment]
This doesn't appear to be a TaN issue by the looks of it, rather, something in your setup is preventing Forge from being able to load our ASM stuff correctly. Since none of us use Linux we're probably not going to be able to help much here, but my guess would be that either Java or some of Forge's dependencies aren't installed correctly, and you should try installing it again. Also why is your forge jar named craftbukkit.jar?

**Comment by sverinn** [comment]
I apologize for this major delay in my answer. Though it may not be relevant anymore, there's some extra information:

> something in your setup is preventing Forge from being able to load our ASM stuff correctly

The same setup works fine without TAN mod, but crashes when it's installed.

> Also why is your forge jar named craftbukkit.jar?

It's because the hosting I used required an executable to have this particular name to work. The environment was latest (at the time i used this setup) unmodified FML.

I don't know how your mod works in terms of code but I believe the error occurs because TAN calls for a Java function that uses some OS feature which is not present in Gentoo.
