### ISSUE TITLE
Campfires dont work

### ISSUE THREAD

**Issue by Flybuild** [Glitchfiend/ToughAsNails#479]
Alright so for some reason, despite me being literally directly next to a campfire, the temperature of the charactor still goes down. Here is proof of the issue: http://prntscr.com/j5cczk

**Comment by Forstride** [comment]
Need a bit more info...What season is it?  What version are you using (Since temperature values were balanced a lot more recently)?

Anyway, I'm just gonna close this because I know for a fact that they do work.  A campfire by itself isn't going to save you if you're outside in the middle of winter though.

**Comment by Flybuild** [comment]
Im using the most recent version (i believe) and It's either early or mid spring.
Im also underground (though, not deep underground)

Also, I'm in a Taiga biome.

A couple side notes, the bug fixed itself after restarting the game and it was night-time when it happened.
