### ISSUE TITLE
Can this work without Biomes A Plenty [More Info Please Don't Remove This.]

### ISSUE THREAD

**Issue by ayakaka** [Glitchfiend/ToughAsNails#501]
Okay so for some reason when I did happen to use this mod without biomes it did not work it just crashed.
I am using **forge-1.12.2-14.23.3.2655-universal.** And the only other mods I have are just simple item mods could this be conflicting. There seem to be no conflicts, some help would be appreciated.

[crash-2018-04-24_21.15.25-client.txt](https://github.com/Glitchfiend/ToughAsNails/files/1945123/crash-2018-04-24_21.15.25-client.txt)
**_Or if you don't want to add another file._**
https://anotepad.com/notes/xerbw5

**Comment by ttamttamS** [comment]
What's your config file look like? It could be referencing BoP biomes. I'm running serene seasons and TaN w/o BoP and haven't had this crash.

**Comment by QAngelusQ** [comment]
I don't know how I got this problem exactly, but I fixed it by deleting the "ToughAsNails" config folder and running the game again (I was running serene seasons, Biomes o' plenty and Tough as Nails)

**Comment by Nerodon** [comment]
I can confirm what QAngelusQ is saying. Easy repro steps:
- Install TaN and BoP together and run the game (Serene seasons too? haven't tested without)
- remove BoP mod and start the game

TaN will crash on start, 
the configs are to blame as it tries to reference or act on BoP in some way, deleting the TaN config folder fixes the issue. The issue here is that TaN should check if BoP is no longer present and avoid using BoP specific configs if the mod is missing.
