### ISSUE TITLE
Thermometer and Rain Collector Recipes 

### ISSUE THREAD

**Issue by speef33** [Glitchfiend/ToughAsNails#510]
I currently have a private server running: Forge .2655, TAN 1.12, AppleCore 1.12.2, coroutil 1.12.2, Pam's HarvestCraft 1.12.2, Optifine 1.12.2 hd_u_d1, The Spice of Life 1.12.1, Weather2 1.12.2-2.5.5 and I can not craft the Thermometer or Rain Collector with the given recipes on the TAN Wiki....anyone else encountering these issues and if so, is there a workaround/fix? Thank you for replies!

-Speef33

**Comment by Forstride** [comment]
The recipes were changed fairly recently, so if you're on an older version, the wiki isn't going to reflect that.

Previous thermometer recipe used diamonds instead of glass, and quartz instead of redstone, and the rain collector used an iron bar instead of string, and had an empty slot where the bucket is in the current recipe.

**Comment by speef33** [comment]
Thank you very much for quick and to the point reply! Can you by chance
send me or point me to the recipes in the version my friends and I are
using on our server? (See orginal post I made for version number)...Or is
it safe to update TAN Mod without fear of losing all our progress up to
now? I can not find a definitive answer about that anywhere online. Also we
thank you for a challenging and immersive mod!

Best Regards,
Speef33
