### ISSUE TITLE
Crash when look inside chest.

### ISSUE THREAD

**Issue by madhatr** [Glitchfiend/ToughAsNails#512]
MC 1.12.2
1.12.2-forge1.12.2-14.23.3.2678
ToughAsNails-1.12.2-3.1.0.116-universal

Destroyed chest and crashed when the items became visible.

[crash-2018-05-08_10.52.10-client.txt](https://github.com/Glitchfiend/ToughAsNails/files/1984183/crash-2018-05-08_10.52.10-client.txt)

**Comment by Forstride** [comment]
It's because canteens only have 2 possible water types now instead of 3.  I'm not entirely sure how _you_ can fix this, but there's really nothing we can do about it since you're using a new version on an old world.  You'd have to find some way to remove the canteen item entity in the world.

**Comment by KnightMiner** [comment]
Its actually pretty easy for you to fix it, just add a catch [here](https://github.com/Glitchfiend/ToughAsNails/blob/TAN-1.12.x-3.x.x/src/main/java/toughasnails/item/ItemCanteen.java#L156) for invalid metadata. Since you can easily spawn itemstacks with invalid metadata you should never crash from an old metadata.

**Comment by madhatr** [comment]
So will there be a fix for  this?
