### ISSUE TITLE
[Bugs/Suggestions] Miscellaneous

### ISSUE THREAD

**Issue by DrakoAlcarus** [Glitchfiend/ToughAsNails#513]
1. Pure Water Bug: Placing purified water into the world turns normal water into stone as if it were lava on top of water. Pure water also turns to stone in regular water. Possible suggestion would be to make it behave like Destabilized Redstone (Thermal Foundation), and it turns into a normal source block if it sits in with normal water for a short time.

2. HUD Bug: In third person, the water droplets on the HUD have black squares.

3. Minor Item Bug: grabbing a pure water source block in JEI turns into a bucket instead of giving you the source block.

4.Source Block Blues: There seems to be no purpose for the pure water block, as using the canteen does not do anything, and bottles scoop up normal water. There is no current way to convert buckets to bottles.

5. Thermal Expansion Compatibility: Magma Crucible recipes to boil the water from normal to pure, Fluid Transposer recipes to bottle the water either in bottles or canteens, and Fluid Reservoir compatibility to auto-fill the canteen with water or pure water (on Refilling Equipment mode).

Knowing this mod is newer, these might already be planned, but these are some ideas I've had/bugs I've encountered.

**Comment by Forstride** [comment]
1) Liquids need to have "touching" interactions, otherwise they look really weird directly next to each other if they have varying height levels.

2) Can confirm, thanks

3) Likely nothing we can do about it, as we just use Forge's fluid system, and everything is handled from there.

4) I'm aware that the source block interactions are broken.  There doesn't seem to be an actual bottle fill event in Forge, so I'm not sure how we're going to handle that.

5) Additional mod integration is pretty low on our to-do list.  Minecraft 1.13 will be coming out soon (Probably later this month) as well, so we'll be focusing all of our efforts on updating our mods to that as soon as possible.

**Comment by DrakoAlcarus** [comment]
1. I'm not sure how thermal expansion does it. They have oil and destabilized redstone touch water safely without any block making, and they are shorter than water.
![2018-05-11_00 24 08](https://user-images.githubusercontent.com/12781728/39911936-e87bd4a4-54b1-11e8-8abd-b64ed563c94c.png)
![2018-05-11_00 24 30](https://user-images.githubusercontent.com/12781728/39911937-e8958d9a-54b1-11e8-8215-68b315e4b587.png)

2. No problem

3. That's fair enough. It's also something JEI does with all fluids. That's my bad.

4. I'm thinking cauldrons would help, unless they can only hold water. I would guess if they could hold pure water, you wouldn't really need Rain Colledtors. Would give them another use. Also crafting a bucket with 3 or 4 bottles would work.

5. Understood. Do you plan on doing it later when Thermal Expansion finishes?

**Comment by KnightMiner** [comment]
Cauldron can only hold vanilla water by default, though adding my mod Inspirations allows you to fill it with a purified water bucket then empty it with bottles.
