### ISSUE TITLE
Hoppers remove items from the fuel/water slot of a water purifier instead of only the output slot

### ISSUE THREAD

**Issue by Xicad** [Glitchfiend/ToughAsNails#684]
## Bug Report

Hoppers remove items from the fuel/water slot of a water purifier instead of only the output slot</br>

### What's the issue you encountered?

After placing a hopper below a water purifier to try and make an automatic one (similar to an auto smelter in vanilla minecraft), the charcoal just gets pulled out from the hopper that's below it. I also tested it with only tough as nails installed and it still happened. </br>

### How can the issue be reproduced?

Place a hopper below a water purifier, then put charcoal in the water purifier. The charcoal will go into the hopper. </br>

### Logs

https://gist.github.com/Xicad/fd55afca7cef117009c2e0d2b40d6dd6 </br>

### Mod Version
ToughAsNails-1.16.5-4.0.1.23</br>

**Comment by lilmayu** [comment]
You can also put stuff into the output slot with a hopper.

**Comment by Oct0bass** [comment]
Yeah this does not seem to be designed with hoppers in mind at all.  Hoppers, both input and output, will pull from/insert into all three slots (input, output, and fuel).  They also seem have weird behaviors with items types, when I put water bottles into the hopper they go into all three slots, but for some odd reason charcoal goes into *only* the *input* slot.  I'm playing in a fairly large pack so I'll have to test with just TAN, but TAN itself certainly has odd behaviors.

Edit: Completely forgot I'm playing a 1.16.5 version of TAN.  This issue may or may not behave differently in 1.17 (or it maybe fixed idk but I assume it's not since this issue's status hasn't changed)

**Comment by Adubbz** [comment]
This has been fixed in the 1.18 version of the mod which will be released soon.
