### ISSUE TITLE
Better configs

### ISSUE THREAD

**Issue by Raycoms** [Glitchfiend/ToughAsNails#711]
### What feature are you suggesting?

There should be a bunch of additional config possibilities for modpack makers:

a) Speed at which the water bar empties (speed up or speed down from default)

b) Level at which hearts regenerate 
(so that we could set it to above 50% for example)

### Why should it be added?

At the given moment water goes down very quickly and you spend half of the time drinking water constantly to stay afloat, having these options would make it much more useful in modpacks.

**Comment by Adubbz** [comment]
There already is a config option for changing the speed at which thirst reduces, it’s the exhaustion_threshold.

**Comment by Raycoms** [comment]
#The threshold at which exhaustion causes a reduction in hydration and the thirst bar.
	#Range: 0.0 ~ 1.7976931348623157E308
	exhaustion_threshold = 8.0
	

Increase it to make it less, or decrease it?|

**Comment by Adubbz** [comment]
A higher threshold will make thirst decrease slower. The inverse is true for a lower threshold.

**Comment by Barerock** [comment]
As an alternative to this, it would be nice to be able to access these configs from Forge's mod menu, or Create's more advanced config viewer, which it can do with more flexibility than Forge. 1.18.1 doesn't seem to have _any_ useful config options that are immediately accessible and testable in-game. 

Option choices I would like to see in-game include the above thirst threshold, temperature thresholds and tweaks, healing thresholds, and water purity RNG tweaks. Not to degrade your current work, of course, it is quite good. Everyone has their preferences to how hard their game should be, and currently this mod gives a harsh, set in concrete difficulty/mechanic menu that puts me off of an otherwise awesome system.

**Comment by Adubbz** [comment]
Closing this as there is now an option to disable thirst affecting health generation entirely (and by default it now does not affect health regeneration)
