### ISSUE TITLE
More configuration

### ISSUE THREAD

**Issue by xz123456xz** [Glitchfiend/ToughAsNails#722]
Add configurable items to quench your thirst.
There are other mods that can be configured by themselves.
Thank you~~

**Comment by Forstride** [comment]
Thirst-quenching items can be added with a datapack.  The data folder in the .jar contains the default tags you can base it off of.

**Comment by xz123456xz** [comment]
@Forstride  Where is an example of making a data package? Your wiki does not provide a tutorial.

**Comment by Forstride** [comment]
We're not providing an example, but it's the same as making a datapack for any other tags.  Just look through the .jar to find the appropriate ones, removing the existing values, and replace them with your own.  And then package them into a datapack.

Ideally though, you should be contacting other mod authors to add support for TAN to their mods, because that's the entire reason we switched to a tag-based system instead.
