### ISSUE TITLE
Config and Datapack additions for 1.18.1

### ISSUE THREAD

**Issue by Tyrius1** [Glitchfiend/ToughAsNails#729]
I have a few requests so I hope you don't mind me just puting all of them in this one post.
I appreciate you taking the time to read this and even if none of them get picked up, I appreciate you guys and your contribution to the Minecraft communities! 
-----------------------------------------------------------------------------------------------------------------------------------------
Request 1:
### (1a) What feature are you suggesting?
[blocks]: 
[ This is a 3 part request including datapack additions and changes. 
Move the blocks config entry to data. 
Make cooling_blocks.json and heating_blocks.json folders and give each item it's own json.
Add ability to adjust how much temperature change each block offers.
data/toughasnails/tags/blocks/heatingblocks/campfire.json ]</br>

item:campfire
range: 7
output: +1

### (1a) Why should it be added?

[ Describe the benefits of implementing this feature. ]</br>

So every time i've added tough as nails into my pack i've heard someone ask me to add furnace to heating_blocks.json. I get it. It really does make sense. If I stand next to my oven/furnace in my home it definitely does have heat radiating off of it. However, I feel odd adding it to the list cause it then produces the same amount of heat at the same distance as say a campfire. 

You could almost take this a step further and say: 
The campfire produces less heat in the snowy biomes or whitelisted biomes. 
It is definitely harder to start and keep a fire up in the snow. 
You could maybe argue the fire would produce less heat in the snow. 
God I guess you can take that even further now..

item:campfire
weather: snow: -1
range: 1-1 = +3 (where if you are within 1 block of the campfire you gain +3 heat) 
range: 2-3 = +2 (where if you are within 2-3 blocks of the campfire you gain +2 heat) 
range: 4-7 = +1 (where if you are within 4-7 blocks of the campfire you gain +1 heat) 

-----------------------------------------------------------------------------------------------------------------------------------------

Request 2:
### (2a) What feature are you suggesting?
[client.toml]:
GUI Offset addition for the temperature overlay. 
_Using a custom hud mod and everything looks so perfect to me. I just wanna move the temperature overlay up like 1 or 2 notches._

### (2b) Why should it be added?
It should be added so that anyone who uses custom HUD mods can tweak the temperature overlay.

-----------------------------------------------------------------------------------------------------------------------------------------

Request 3:
### (3a) What feature are you suggesting?
[server.toml]:
Add a config to enable x effect to the player if they drink from the water with their bare hands.

### (3b) Why should it be added?
Because if you went out into a jungle or one of the other biomes that Minecraft offers in real life and drank sitting water with your bare hands.. You would get diarrhea.. at the very least. If you are lucky. "Imagine what you would catch drinking water from the ominous woods open handed..."
I get that adding effects may be out of the scope of tough as nails or maybe not idk but maybe with some really nasty modded potion effects it'll teach people that you have to boil water before you drink it.

**Comment by Tyrius1** [comment]
"it'll teach people that you have to boil water before you drink it." ~ thats right.. people do it on every survivor style show but this 1 change will tip the balance for the entire world!

**Comment by Forstride** [comment]
In regards to the 1st suggestion, that probably isn't gonna happen.  Blocks can't have individual temperature ranges due to how the proximity search works.  Additionally, the mod is balanced around blocks either cooling or heating by 1 (Or none), and it would be a lot harder otherwise.  Likewise, getting heated or cooled by one is enough to put you back into a safe temperature range.  Only the 2 extremes will ever harm you.  Also having them give different values based on the weather or biome would be incredibly confusing to players.

2nd suggestion is entirely possible and can be added in a future update.  If you want, I'd prefer you open a separate issue for that so we can keep track of it more easily, since I'm going to be closing this one.

As for the 3rd suggestion, we don't support drinking by hands by default, so we're not going to add any additional functionality to that.  The option is only there because whined to us to keep it in, and it's not a factor for how we balance the mod.
