### ISSUE TITLE
Make dehydration more real

### ISSUE THREAD

**Issue by MataraOkina** [Glitchfiend/ToughAsNails#734]
### Overview

Hello, author.

1.I want to add a switchable option: when the player continues to drink dirty water, he will get level 2 "dehydration", which will make him more dehydrated, and drinking dirty water will not increase water.

2.Drinking Potion will not cause dehydration.

### Why would this feature be useful?

1.Because players only need to carry glass bottles (or canteen) and a bucket of water, they can realize unlimited amount of water in the process of survival. This makes the cost of obtaining water too low. I want to add that to make survival more difficult. At the same time, it is also a switchable option, and you can get different experiences according to your choice.

2.In brewing stand,the potion brewed  should be clean because blaze powder temperature is very high. This is also more in line with people's common sense.

**Comment by Forstride** [comment]
The mod isn't meant to be realistic.  It has "realistic" survival mechanics, but with a simplistic/gameplay-focused take.

As for potions having a poison chance, that's mainly because water bottles use the same item that potions do, and we can't discern between NBT values since we use item tags for thirst.
