### ISSUE TITLE
Crash on game boot

### ISSUE THREAD

**Issue by zachsai** [Glitchfiend/ToughAsNails#741]
### What's the issue you encountered?

Crash

### How can the issue be reproduced?

i dont know the reason for crash

### Logs

https://pastebin.com/TNN3pSZy

### Mod Version

7.0.0.71

**Comment by Adubbz** [comment]
This is an issue with some other mod you have installed breaking item colour registration. There’s really nothing that can be changed on TAN’s side to fix this.

**Comment by zachsai** [comment]
Any idea which mod?

**Comment by zachsai** [comment]
![image](https://user-images.githubusercontent.com/63996164/164957743-92f7af0f-9002-4231-b499-b08a176b0605.png)

**Comment by zachsai** [comment]
Maybe a change that TAN could do? This came from a collaborator on the forge discord

**Comment by lukebemish** [comment]
I'm going to make a wild guess here, as I can't look at the source code and am not sure what other mods might be involved: Some other mod, I suspect, is doing something with item colors during loadcomplete. This is normally perfectly fine practice, since color handlers should all be registered by then. However, since TAN registers item colors then, instead of during ColorHandlerEvent.Item, it messes stuff up. In theory, this should be fixable from TAN's end by switching where color handlers are registered to use the proper event.

**Comment by Adubbz** [comment]
Both BOP/TAN have been changed to use the event now. I commented on the relevant BOP issue but not this one
