### ISSUE TITLE
Guide for this mod

### ISSUE THREAD

**Issue by ilovehorrorcats** [Glitchfiend/ToughAsNails#748]
### Overview

In game wiki could tell us what blocks cool you the best and what blocks warm you up the best and info about status effects and stuff

### Why would this feature be useful?

It would help me find the perfect way to keep a place cool or warm

**Comment by iobiarg** [comment]
Really need more documentation on this mod, in the middle of the plains, getting frozen when snowing and burned in summer, a way to keep the house at a safe temperature... (serene season installed) and the custom armors provided by this mod don't allow to wear actual pve protection... maybe you could sth like "Survivalist" that allowed you to pad any metal o modded armor with the isolation armor from the mod.

**Comment by Stackedactor** [comment]
I would really love to use this mod, but I can't find documentation of how to craft the in game items anywhere. They aren't searchable in game and the wiki just describes the items vaguely without any recipes or screenshots to show how to make them. When I found myself scouring random blog posts for screenshots, I decided it just wasn't worth the effort. I know it's a great mod because Ive seen it featured in many videos, but how are you supposed to get started when you aren't told how to make the most basic of essentials for survival?

**Comment by Forstride** [comment]
I've added documentation for most basic things in the mod on our wiki (https://github.com/Glitchfiend/ToughAsNails/wiki), including crafting recipes, what every block/item does, and so on.  Still have a bit more stuff that could probably be added, but I think it's mostly sufficient for now (Certainly compared to how it was at least).
