### ISSUE TITLE
Disable temperature/thirst tooltips if their respective features are disabled

### ISSUE THREAD

**Issue by zachsai** [Glitchfiend/ToughAsNails#803]
### Overview

Add a feature where if the server config for either:

[toggles]
	#Enable or disable thirst.
	enable_thirst = false
	#Enable or disable temperature.
	enable_temperature = false

If set to false, the items from those features are disabled (creative inventory hidden for armor and canteens, etc)
Same goes for their recipes if possible, but just jei hiding would be nice

### Why would this feature be useful?

Better modpack integration and granular usage.

**Comment by Forstride** [comment]
That's not really feasible since recipes are all data-driven, and not registering the items would lead to warnings being spammed in the logs every time you load a world.  It also seems unnecessary for creative mode specifically since thirst/temperature don't even do anything to begin with there.

We can disable the temperature/thirst tooltips for items if the respective features are disabled, but I don't think we can really do much more than that.
