### ISSUE TITLE
Furnaces, Blast Furnaces, and Smokers heating the player up.

### ISSUE THREAD

**Issue by Coffe-e** [Glitchfiend/ToughAsNails#866]
### Overview

So, I can't remember if it was a different temperature mod, but I find it weird that Furnaces/Blast Furnaces/Smokers dont heat you up while they're running, despite them logically being a significant source of heat. (Smelting metal, cooking food)

### Why would this feature be useful?

Not having to rush either specifically: A campfire, the edible warmth item, or wool clothes would be really nice early game, since while you get furnaces immediately, they're timed rather than infinite in the case of a campfire.

**Comment by Forstride** [comment]
They don't give off heat by default because they're too integral to Minecraft's progression, and it wouldn't be good to have furnaces potentially overheat players in desert biomes for example.  It's the same reason torches don't give off heat either.

You can change it with a datapack if you really want, but we don't plan to make them give off heat by default.
