### ISSUE TITLE
Add API for other mods to use

### ISSUE THREAD

**Issue by Forstride** [Glitchfiend/ToughAsNails#9]
Add an API so other mods can:

- Assign heat/cold levels to armor for when the player is wearing it

**Comment by InkDragon** [comment]
Would it be possible when this is added to have the option to manually register and set the values for items via a config? So that if a mod author doesn't use your API players can still set up and use your mod with the other. 

eg if Harvestcraft didn't adopt your api users would be able to manually add and set the values for harvestcraft drinks to restore thirst

**Comment by Forstride** [comment]
https://github.com/Glitchfiend/ToughAsNails/issues/26#issuecomment-227032255

**Comment by Wabbit0101** [comment]
Howdy folks. Any progress on whether this will be done for 1.11.2 (seems to have missed the assigned milestone for 2016 :) ).

**Comment by RANDOM800** [comment]
I want to just know if you are going forward on this because as a modpack creator it is really important.

**Comment by Forstride** [comment]
Well as of now, you can add temperature values to blocks/materials, and add hydration values to any items.  The only thing missing is giving temperature values to armor.

**Comment by XminuS13** [comment]
Well hello there. How do I add hydration values to items? I tried to add some items into the drink_stats JSON, but it made my game crash.
Here's the config file:
https://pastebin.com/28xuVyiu
Would like to know, and love your mod anyways!
